# Generated by Django 4.2.11 on 2024-04-24 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first", models.CharField(max_length=100)),
                ("last", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=30, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["id"], name="core_contac_id_4b5684_idx")
                ],
            },
        ),
    ]
